### ISSUE TITLE
[MCOMPILER-190] No compile errors with plexus-compiler-eclipse

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-compiler-plugin#475]
**[Peter Palmreuther](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pitpalme)** opened **[MCOMPILER-190](https://issues.apache.org/jira/browse/MCOMPILER-190?redirect=false)** and commented

I'm trying to make use of plexus-compiler-eclipse by configuring maven-compiler-plugin (3.0) with a compilerId of 'eclipse' and dependency to plexus-compiler-eclipse, version 2.0 (couldn't select 2.0 in affects version above, so I left blank).
I have java classes that definitely should raise a compiler error.

'mvn compile' gives

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.0:compile (default-compile) on project sample: Execution default-compile of goal org.apache.maven.plugins:maven-compiler-plugin:3.0:compile failed: basedir ${project.basedir}/target/classes does not exist

on a clean project. Nothing else, no compiler error with respect to erroneous class. And in fact no compiled class.

But more critical to mee seems compilation on a non-clean project, i.e. 'target/classes' exists.

Output of 'mavn compile' than is

[INFO] --- maven-compiler-plugin:3.0:compile (default-compile) @ sample ---
[INFO] Changes detected - recompiling the module!
[WARNING] Dummy.java:[5] Type mismatch: cannot convert from Integer to String
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS

I've attached a sample project which can be used to reproduce the behavior.
1. Extract to an empty directory
2. chdir to this directory
   2.a if in doubt: mvn clean
3. mvn compile
   4.a error message about non-existent output directory
4. mkdir -p target/classes
5. mvn compile
6. see above mentioned warning, but build "succeeds" (of course no class file was generated)

---

**Affects:** 3.0

**Attachments:**
- [pce.tar.gz](https://issues.apache.org/jira/secure/attachment/12714940/pce.tar.gz) (_795 bytes_)

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

fixed.
Thanks for the test project !

**Comment by desruisseaux** [comment]
The test case provided by this issue is not executable anymore since the Maven compiler plugin 4.x does not use Plexus anymore. However, since this test case was trying to use the Eclipse compiler, it can be refactored as the new test case required by #904.
